### PR TITLE
compile bug fix

### PR DESCRIPTION
**Pull request by KiSooLee**
Bug fixed for following files
include/gammagammaleptonpair.h
src/gammagammaleptonpair.cpp

### CODE REVIEW

**Comment by KiSooLee** [comment]
+1

**Comment by smuzaffar** [comment]
@KiSooLee , if this needs to go in cmssw then can you please create a spec file and make a PR for cms-sw/cmsdist?

**Comment by KiSooLee** [comment]
Yes, I will make spec file.
It is just first step to make a PR for cms-sw/cmsdist.
There are some more things to be modified.

**Comment by KiSooLee** [comment]
some files updated to use CLHEP random number

**Comment by KiSooLee** [comment]
PR for cms-sw/cmsdist is made

**Comment by ghost** [comment]
@KiSooLee I believe this patch needs to go in to make your CMSDIST pr working. Am I right?

**Comment by KiSooLee** [comment]
Yes, right

**Pull request merged**
