### PR TITLE
FindCLHEP.cmake updated based on FairRoot

### PR DESCRIPTION
**Pull request by KiSooLee**
FindCLHEP.cmake updated based on FairRoot

### CODE REVIEW

**Comment by KiSooLee** [comment]
+1

**Comment by KiSooLee** [comment]
Could you please merge this pull request so that I can test spec file?

**Comment by davidlt** [comment]
NAK, this one had to rejected.

```
+Find_Program(CLHEP_CONFIG_EXE NAMES clhep-config PATHS
 +   /cvmfs/cms.cern.ch/slc6_amd64_gcc491/external/clhep/2.2.0.4/bin
```

We cannot allow hardcoded paths to CVMFS, CLHEP version and architecture.

**Comment by KiSooLee** [comment]
OK I see what you mean.
Let me modify and check again in local.

**Pull request merged**
