### PR TITLE
compressed commit of CLHEP related modification

### PR DESCRIPTION
**Pull request by KiSooLee**
compressed commit of CLHEP related modification

### CODE REVIEW

**Comment by davidlt** [comment]
According to GIT there are already merge conflicts.

**Comment by KiSooLee** [comment]
How can I see the detail message of conflict?

**Comment by KiSooLee** [comment]
Ok I found the reason of conflict.
To make first pull request I did following sequence.
1. fetch cms-externals:cms/r193 to CmsHI:cms/r193
2. copy from CmsHI:cms/r193 to lxplus
3. modify and push to CmsHI:patch1
4. merge CmsHI:patch1to cms-externals:cms/r193
Actually there was a merged pull request.
So now CmsHI:cms/r193 is different from cms-externals:cms/r193
Therefore this pull request which is start from CmsHI:cms/r193 makes conflict with cms-externals:cms/r193.
Then how can I update CmsHI:cms/r193 to make same version with cms-externals:cms/r193?

**Comment by davidlt** [comment]
@degano @smuzaffar could you take care?

**Comment by KiSooLee** [comment]
I can fork it to another repository and make correct pull request.
But its not radical solution.
Maybe there is a way to update forked package when the original package is updated.

**Comment by smuzaffar** [comment]
@KiSooLee , I am not sure what you are trying to achieve here. PR #1 has already been merged. So if you have any changes on top of that then please make a PR with only those changes.

**Comment by ghost** [comment]
@KiSooLee No need to create another repository. From the one existing just make sure to `git pull --rebase` to update and THEN apply your patch and push again. Please.

**Comment by KiSooLee** [comment]
I mean if I fork  cms-externals:cms/r193 before merge PR#1, how can I synchronize my fork repository to cms-externals:cms/r193 after PR#1 is merged?

**Comment by ghost** [comment]
The branch in the fork is automatically updated to the tip of the branch, therefore PR 1 will be already in place. As it is already in place in CmsHI/cms/r193.

**Comment by KiSooLee** [comment]
But if you compare these two link, they are not in place.
First link is cms-externals:cms/r193.
Second link is CmsHI:cms/r193.
They are same file and same line but different.
https://github.com/cms-externals/starlight/blob/cms/r193/src/gammagammaleptonpair.cpp#L129
https://github.com/CmsHI/starlight/blob/cms/r193/src/gammagammaleptonpair.cpp#L129

**Comment by smuzaffar** [comment]
@KiSooLee , do something like this

```
git clone git@github.com:CmsHI/starlight.git
cd starlight
git remote add cms git@github.com:cms-externals/starlight
git fetch cms cms/r193:clhep-fixes
git checkout clhep-fixes
## make your changes
git commit -a -m '<commit message>'
git push origin clhep-fixes
```

then use CmsHi/clhep-fixes to make a PR.

**Comment by KiSooLee** [comment]
Oh!! Thank you it makes same files with cms-externals:cms/r193.

**Comment by KiSooLee** [comment]
Let me make new pull request with CmsHi/clhep-fixes

**Pull request closed without merging**
